# Generated by Django 2.2 on 2019-04-28 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_users_type_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='picture',
            new_name='photo',
        ),
    ]
